version: '3.4'

services:
    simplewebapi:
        image: zalex0/simplewebapi:latest
        depends_on:
            - "postgresql_database"
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:80"
        environment:
            DB_CONNECTION_STRING: "host=postgresql_database;port=5432;database=simplewebapi_db;username=simplewebapi;password=simplewebapi"

    postgresql_database:
        image: postgres:latest
        environment:
            - POSTGRES_USER=simplewebapi
            - POSTGRES_PASSWORD=simplewebapi
            - POSTGRES_DB=simplewebapi_db
        ports: 
            - "5432:5432"
        restart: always
        volumes:
            - database-data:/var/lib/postgresql/data/
            - ./initdb.sql :/docker-entrypoint-initdb.d/initdb.sql

volumes:
    database-data:
    pgadmin: